# Labeler configuration

branding:
  - changed-files:
      - any-glob-to-any-file: "branding/**/*"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - README.md
          - LICENSE
          - "docs/**/*"
          - WIKI.md

workflows:
  - changed-files:
      - any-glob-to-any-file: ".github/workflows/**/*"

automation:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/scripts/**/*"
          - build.sh
          - ".Jules/**/*"

templates:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/ISSUE_TEMPLATE/**/*"
          - .github/PULL_REQUEST_TEMPLATE.md
