size:small:
  - changed-files:
    - count-lte: 10
size:medium:
  - changed-files:
    - count-gt: 10
    - count-lte: 50
size:large:
  - changed-files:
    - count-gt: 50
documentation:
  - docs/**/*
  - "*.md"
scripts:
  - scripts/**/*
  - build.sh
workflows:
  - .github/workflows/**/*
