name: Analyze Build Efficiency
on:
  push:
    paths:
      - '.github/workflows/kiba.yml'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  analyze-eff:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Scan
        shell: bash
        run: grep "apt install" .github/workflows/kiba.yml | sort | uniq -c
