name: Analyze PR Size
on:
  pull_request:
permissions:
  pull-requests: write
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  analyze-size:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Size
        shell: bash
        env:
          PR_ADDITIONS: ${{ github.event.pull_request.additions }}
        run: echo "PR Size additions: $PR_ADDITIONS"
