name: Audit Python Docstring Style

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  audit:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - name: Check docstrings
        run: |
          grep -rE "def .+\):" . --include="*.py" | grep -v '\"\"\"' && (echo "Docstrings required for all functions" && exit 1) || exit 0
