name: Audit Build Su C Grouping

on:
  push:
    paths:
      - 'scripts/kibaos_build.sh'
  pull_request:
    paths:
      - 'scripts/kibaos_build.sh'

jobs:
  audit:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - name: Check command grouping
        run: |
          grep "su -c" scripts/kibaos_build.sh | grep -E "\(&&|\|\|\)" || (echo "Grouping recommended for chained su -c commands" && exit 1)
