name: Audit Shell ShellCheck Disable Comment

on:
  push:
    paths:
      - '**.sh'
  pull_request:
    paths:
      - '**.sh'

jobs:
  audit:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - name: Check ShellCheck disable comments
        run: |
          grep -rn "# shellcheck disable=" . --include="*.sh" | grep -v "Rationale:" && (echo "shellcheck disable should include a Rationale comment" && exit 1) || exit 0
