name: Audit Markdown No Fixme

on:
  push:
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'

jobs:
  audit:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: tr""ue
      - name: Check for FIXME
        run: |
          grep -rn "\bFIXME\b" . --include="*.md" && (echo "Documentation should not contain FIXME markers" && exit 1) || exit 0
