name: Audit Repo No Symlink To Self

on:
  push:
    branches: [main]
  pull_request:

jobs:
  audit:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
        with:
          persist-credentials: false
      - name: Check circular symlinks
        run: |
          find . -type l -exec test ! -e {} \; -print | grep . && exit 1 || exit 0
