name: Audit Build Calamares Sidebar

on:
  push:
    paths:
      - "scripts/kibaos_build.sh"

jobs:
  audit:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Check Sidebar
        run: |
          grep "SidebarBackground:        \"#282a36\"" scripts/kibaos_build.sh
