name: Audit Build GRUB Timeout

on:
  push:
    paths:
      - "scripts/kibatv_build.sh"

jobs:
  audit:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
heckout@11bd71901bbe5b1630ceea73d27597364c9af683/a         with:
          persist-credentials: false
      - name: Check Timeout
        run: |
          grep "set timeout=5" scripts/kibatv_build.sh
