name: Audit Build Konsole Opacity

on:
  push:
    paths:
      - "scripts/kibatv_build.sh"

jobs:
  audit:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
heckout@11bd71901bbe5b1630ceea73d27597364c9af683/a         with:
          persist-credentials: false
      - name: Check Opacity
        run: |
          grep "Opacity=0.95" scripts/kibatv_build.sh
