name: "Audit: Root Password"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Audit: Root Password"
        run: |
          grep "root:" build.sh | grep -q "password" && { echo 'Error: Root password should not be set in build.sh'; exit 1; } || exit 0
