name: Audit Shell Mktemp Usage

on:
  push:
    paths:
      - '**.sh'
  pull_request:
    paths:
      - '**.sh'

jobs:
  audit:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - name: Check for hardcoded /tmp
        run: |
          grep -rnE "\b/tmp/.[^[:space:]]*" . --include="*.sh" | grep -vE "\bmktemp\b" && (echo "Use mktemp instead of hardcoded /tmp paths" && exit 1) || exit 0
