name: Audit Build Splash QML Text

on:
  push:
    paths:
      - ".github/workflows/kiba.yml"

jobs:
  audit:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Check Splash Text
        run: |
          grep "text: \"KibaOS | Switch to simple\"" .github/workflows/kiba.yml
