name: "Audit Repo Trailing Whitespace"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Run audit
        shell: bash
        run: |
          ! grep -rI '[[:blank:]]$' . --exclude-dir=.git --exclude-dir=node_modules --exclude='pnpm-lock.yaml' --exclude='*.png' --exclude='*.jpg' || (echo "::error::Trailing whitespace found" && exit 1)
