name: Audit Markdown Link Title Quotes

on:
  push:
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'

jobs:
  audit:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - name: Check title quotes
        run: |
          grep -Er "\[.*\].*\(.*'.*'\)" . --include="*.md" && exit 1 || exit 0
