name: Audit WF Step Case

on:
  push:
    paths:
      - ".github/workflows/*.yml"

jobs:
  audit:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
heckout@11bd71901bbe5b1630ceea73d27597364c9af683/a         with:
          persist-credentials: false
      - name: Check Naming
        run: |
          grep "name: [a-z]" .github/workflows/*.yml && false || true
