  issues:
    timeout-minutes: 5
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  assign:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign
        uses: pozil/auto-assign-issue@98904791e8312015508a8f6d713c711200259b58
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ github.actor }}
          allowSelfAssign: true
