  push:
    timeout-minutes: 5
    paths:
      - "**/*.py"
  pull_request:
    paths:
      - "**/*.py"

jobs:
  bandit:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683bd71901bbe5b1630ceea73d27597364c9af683
      - name: Install Bandit
        run: pip install bandit
      - name: Run Bandit
        run: bandit -r . -ll
