name: Branding Path Verificator

on:
  push:
    paths:
      - 'branding/**'
      - '.github/workflows/kiba.yml'

jobs:
  verify-paths:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Check Asset References
        run: |
          for asset in branding/*; do
            [ -f "$asset" ] || continue
            filename=$(basename "$asset")
            if ! grep -q "$filename" .github/workflows/kiba.yml; then
              echo "Warning: Asset $filename is not referenced in the build workflow."
            fi
          done
