name: Broken Link Checker
on:
  push:
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  link-checker:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress '**/*.md'
