name: Check Bash Version Compatibility

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check_bash_version_compatibility:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure no bash 4.4+ specific features if targeting older
        run: |
          grep -r "\${parameter@" . --include="*.sh" && exit 1 || exit 0
