name: Check Workflow Security
on:
  push:
    paths:
      - .github/workflows/*.yml
  pull_request:
    paths:
      - .github/workflows/*.yml
jobs:
  audit:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        persist-credentials: false
    - name: Audit Security
      run: 'grep -r "persist-credentials: true" .github/workflows/ && exit 1 || exit
        0

        grep -r "permissions:" .github/workflows/ || exit 1'
    timeout-minutes: 5
