name: Check Notes Naming

on:
  push:
    paths:
      - "Notes/**/*"

jobs:
  audit:
    permissions:
      contents: write
    timeout-minutes: 5
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Verify Naming
        run: |
          ls Notes/NTE-*.md
