name: Check Workflow Strategy Fail Fast
on:
  push:
    paths:
      - .github/workflows/*.yml
  pull_request:
    paths:
      - .github/workflows/*.yml
jobs:
  audit:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        persist-credentials: false
    - name: Check Fail Fast
      run: grep -r "strategy:" .github/workflows/ | xargs grep -L "fail-fast:" | grep
        -v "check-workflow" || exit 0
    timeout-minutes: 5
