name: Check Docs Internal Link Case

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check_docs_internal_link_case:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure internal links are lowercase
        run: |
          grep -r "\](\./[A-Z]" . --include="*.md" && exit 1 || exit 0
