name: Check Branch Naming
"on":
  pull_request:
jobs:
  check:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - name: Verify Branch Name
      run: echo "${{ github.head_ref }}" | grep -vE "^(feat|fix|docs|style|refactor|test|chore|sentinel)/"
        && exit 1 || exit 0
    timeout-minutes: 5
