name: Check Security Contact
on:
  push:
    paths:
      - SECURITY.md
  pull_request:
    paths:
      - SECURITY.md
jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - name: Verify Contact
        run: grep "@" SECURITY.md
