name: Check TODO Format
on:
  push:
  pull_request:
jobs:
  check:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        persist-credentials: false
    - name: Scan TODOs
      run: grep -rn "TOD[O]" . | grep -vE "TODO\((low|med|high|critical)\)" && exit
        1 || exit 0
    timeout-minutes: 5
