name: Check License Year
on:
  push:
    paths:
      - LICENSE
      - LICENSE
  pull_request:
    paths:
      - LICENSE
      - LICENSE
jobs:
  check:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        persist-credentials: false
    - name: Verify Year
      run: grep "2025" LICENSE
    timeout-minutes: 5
