name: Check Docs Terminology
"on":
  push:
paths:
- docs/*.md
- README.md
  pull_request:
paths:
- docs/*.md
- README.md
jobs:
  audit:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        persist-credentials: false
    - name: Check Naming
      run: grep -r "Kiba TV" docs/ && exit 1 || exit 0
    timeout-minutes: 5
