name: Check Action Pinning
on:
  push:
    paths:
      - '.github/workflows/**'
  pull_request:
    paths:
      - '.github/workflows/**'
jobs:
  audit:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      with:
        persist-credentials: false
    - name: Check SHAs
      run: 'grep "uses: actions/" .github/workflows/*.yml | grep -vE "[a-f0-9]{40}"
        && exit 1 || exit 0'
    timeout-minutes: 5
