name: Check Branding Svg Viewbox

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check_branding_svg_viewbox:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure SVG icons have viewbox
        run: |
          grep -L "viewBox" branding/*.svg && exit 1 || exit 0
