name: Close Inactive PRs
on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  close-stale:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/stale@v9
        with:
          stale-pr-message: 'This PR is stale because it has been open 30 days with no activity.'
          days-before-pr-stale: 30
          days-before-pr-close: 7
          stale-pr-label: 'stale'
