  push:
    timeout-minutes: 5
    branches: [main]

jobs:
  manage-contributors:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0
      - name: Update Acknowledgments
        run: |
          echo "Refreshing contributors in ACKNOWLEDGMENTS.md..."
