name: Dependency Review Lockfile

on:
  pull_request:
    paths:
      - 'package-lock.json'
      - 'pnpm-lock.yaml'

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
