name: Docs Image Alt Text Checker
on:
  push:
    paths:
      - '**.md'
jobs:
  check-alt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Check for missing alt text
        run: |
          grep -rnE "!\\[\\]" docs/*.md && { echo "Found images with empty alt text"; exit 1; } || echo "All images have alt text"
