  schedule:
    timeout-minutes: 5
    - cron: "0 0 * * 1" # Every Monday
  workflow_dispatch:

jobs:
  notify-stale-drafts:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
        with:
          script: |
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });

            const drafts = pullRequests.filter(pr => pr.draft);
            for (const pr of drafts) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                body: "👋 This draft PR has been open for a while. Is it ready for a review or still in progress?"
              });
            }
