name: Ensure Notes Gitkeep

on:
  push:
    paths:
      - "Notes/**"
  pull_request:
    paths:
      - "Notes/**"

jobs:
  audit:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Code
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false

      - name: Ensure Notes Gitkeep
        run: |
          [ -f Notes/.gitkeep ] || { echo "Error: Notes/.gitkeep missing"; false; }
