name: First PR Mentor Matching
on:
  pull_request:
    types: [opened]

jobs:
  match-mentor:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pull-requests: write
    steps:
      - name: Detect First-Timer
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          USER=${{ github.event.pull_request.user.login }}
          PR_COUNT=$(gh pr list --author "$USER" --state all --limit 10 --json number --jq '. | length')

          if [ "$PR_COUNT" -eq 1 ]; then
            # Randomly pick a mentor from a predefined list (usually maintainers)
            MENTORS=("WolfTech-Innovations" "maintainer-one" "maintainer-two")
            SELECTED_MENTOR=${MENTORS[$RANDOM % ${#MENTORS[@]}]}

            gh pr comment ${{ github.event.pull_request.number }} --body "Welcome @$USER! Since this is your first PR, I've assigned @$SELECTED_MENTOR as your mentor to help you with the review process. "
            gh pr edit ${{ github.event.pull_request.number }} --add-reviewer "$SELECTED_MENTOR"
          fi
