name: Greetings

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  greeting:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@3c71ce730280171fd1cfb57c00c774f8998586f7
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Hello! Thank you for opening your first issue in KibaTV. We'll get back to you soon!"
          pr-message: "Welcome! Thank you for your first contribution to KibaTV. We'll review your PR as soon as possible."
