name: GSettings Checker
on: [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify GSettings
        run: |
          grep "gsettings set" build.sh | awk '{print $4}' | sort -u
