name: Iso Pkg List No Duplicates

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  iso_pkg_list_no_duplicates:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure no duplicate packages in lists
        run: |
          if [ -f package_list.txt ]; then sort package_list.txt | uniq -d | grep . && exit 1 || exit 0; fi
