  issues:
    timeout-minutes: 5
    types: [opened, edited]

jobs:
  label-components:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Auto Label
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
        with:
          script: |
            const body = context.payload.issue.body.toLowerCase();
            const labels = [];
            if (body.includes('installer') || body.includes('calamares')) labels.push('installer');
            if (body.includes('theme') || body.includes('plasma')) labels.push('theme');
            if (body.includes('shell') || body.includes('zsh')) labels.push('shell');
            if (labels.length > 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                labels: labels
              });
            }
