name: Issue Milestone Reminder

on:
  issues:
    types: [opened]

jobs:
  milestone-reminder:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b
        with:
          script: |
            if (!context.payload.issue.milestone) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                body: "📌 Friendly reminder to assign this issue to a milestone."
              });
            }
