name: Kernel Endpoint Monitor

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check-endpoints:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Verify CachyOS Kernel URLs
        run: |
          REPO_URL="https://api.github.com/repos/Nitrux/linux-cachyos-deb/releases/latest"
          curl -f -I "$REPO_URL" || exit 1
