name: Markdown Code Language Requirement
on:
  push:
    paths:
      - '**.md'
  pull_request:
    paths:
      - '**.md'
jobs:
  check-lang:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Scan for untagged code blocks
        run: |
          find . -name "*.md" -not -path "./node_modules/*" | xargs -r grep -l "^[[:space:]]*\`\`\`[[:space:]]*$" && { echo "Error: Markdown code blocks must have a language tag."; exit 1; } || echo "All code blocks are tagged"
