name: Markdown Link No Space

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  markdown_link_no_space:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure no space between ] and (
        run: |
          grep -r "\] (" . --include="*.md" && exit 1 || exit 0
