  push:
    timeout-minutes: 5
  pull_request:
    branches: [main]

permissions:
  contents: read
    timeout-minutes: 5
  pull-requests: write
    timeout-minutes: 5
  statuses: write
    timeout-minutes: 5

jobs:
  megalinter:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-depth: 0

      - name: MegaLinter
        uses: oxsecurity/megalinter@v8
        env:
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Exclude what we have individual workflows for
          DISABLE_LINTERS: BASH_SHELLCHECK,YAML_YAMLLINT,MARKDOWN_MARKDOWNLINT,JSON_JSONLINT
          # Enable others
          ENABLE_LINTERS: REPOSITORY_DEVICETREE,DOCKERFILE_HADOLINT,SECRET_GITLEAKS
