name: Notify SourceForge Release
true:
  workflow_run:
    workflows:
    - KibaTV Build
    types:
    - completed
    branches:
    - main
jobs:
  notify:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Log Release
      run: 'echo "ISO Build successful. Check SourceForge: https://sourceforge.net/projects/kibaos/files/"

        '
    timeout-minutes: 5
