name: Package List Distro Purity

on:
  push:
    paths:
      - "scripts/kibatv-build.sh"
  pull_request:
    paths:
      - "scripts/kibatv-build.sh"

jobs:
  audit:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Code
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false

      - name: Package List Distro Purity
        run: |
          grep -E "<<.*PACKAGES" scripts/kibatv-build.sh -A 100 | grep -E "pacman|yum|apk" && { echo "Error: non-debian package"; false; } || true
