name: Package List Duplicate Detector

on:
  pull_request:
    paths:
      - '.github/workflows/kiba.yml'

jobs:
  detect-duplicates:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Scan for Redundant Packages
        run: |
          sed -n '/PACKAGES/,/PACKAGES/p' .github/workflows/kiba.yml | grep -v "PACKAGES" | grep -v "^#" | grep -v "^$" | sort | uniq -d
