  validate-co-authors:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: Check commit messages for Co-authored-by
        run: |
          git log origin/${{ github.base_ref }}..HEAD --pretty=%B | grep "Co-authored-by:" | grep -vE "<.+@.+\..+>" && { echo "Error: Invalid Co-authored-by format. Use: Co-authored-by: Name <email@example.com>"; exit 1; } || echo "Co-authors valid"
