  schedule:
    timeout-minutes: 5
    - cron: "0 10 * * 1-5"
  workflow_dispatch:

jobs:
  monitor-latency:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Age
        uses: davideviolante/pr-reviewer-reminder@87c265691c28f09b5523467f394c8e7136709871
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-reminder: 3
