name: PR Task List Checker

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-tasks:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Check for incomplete tasks
        uses: actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b
        with:
          script: |
            const body = context.payload.pull_request.body;
            if (!body) {
              core.setFailed('PR description is empty');
              return;
            }
            if (body.includes('- [ ]')) {
              core.setFailed('There are incomplete tasks in the PR description');
            }
