  check-tasks:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Check for incomplete tasks
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea
        with:
          script: |
            const body = context.payload.pull_request.body;
            if (!body) {
              core.setFailed('PR description is empty');
              return;
            }
            if (body.includes('- [ ]')) {
              core.setFailed('There are incomplete tasks in the PR description');
            }
