name: Prettier
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  prettier:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        shell: bash
        run: pnpm install
      - name: Run Prettier
        shell: bash
        run: pnpm exec prettier --check .
