name: Release Notes Auto-Draft
on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  save-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Save Release Notes
        env:
          RELEASE_ID: ${{ github.event.release.id }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: bash scripts/save_release_notes.sh
