name: Repo No Exec On Configs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  repo_no_exec_on_configs:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure configs are not executable
        run: |
          find . -name "*.conf" -executable | grep . && exit 1 || exit 0
