name: Repo No Symlink To Abs
on:
  push:
  pull_request:
jobs:
  audit:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Check for absolute symlinks
        run: |
          find . -type l -exec ls -l {} + | grep " -> /" && { echo "Absolute symlinks found; use relative paths"; exit 1; } || echo "No absolute symlinks found"
