name: Repo No Mixed Indentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  repo_no_mixed_indentation:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure no mixed tabs and spaces
        run: |
          grep -rE "^ 	|^	 " . && exit 1 || exit 0
