name: Shell Syntax Check

on:
  push:
    paths: ['**/*.sh']
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Syntax
        run: |
          find . -name "*.sh" -exec bash -n {} +
