name: Workflow Permissions Audit
on:
  push:
    paths:
      - '.github/workflows/*.yml'
jobs:
  audit:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      name: Run actions/checkout
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Check for excessive permissions
        run: |
          grep -rn "permissions: write-all" .github/workflows/*.yml --exclude="workflow-permissions-audit.yml" && { echo "Error: write-all permission is prohibited"; exit 1; } || echo "Permissions are restricted"
