name: Workflow Job Timeout Enforcer

on:
  push:
    paths:
      - ".github/workflows/*.yml"
  pull_request:
    paths:
      - ".github/workflows/*.yml"

jobs:
  audit:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    timeout-minutes: 5
    steps:
      - name: Checkout Code
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Workflow Job Timeout Enforcer
        run: |
          ERR=0; for f in .github/workflows/*.yml; do grep -q "timeout-minutes:" "$f" || { echo "Error: $f"; ERR=1; }; done; [ $ERR -eq 0 ]
