name: Workflow Env Naming Convention
on:
  push:
    paths:
      - '.github/workflows/*.yml'
jobs:
  check:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      name: Run actions/checkout
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Verify env naming
        run: |
          grep -rnE "env: [a-z]" .github/workflows/*.yml && { echo "Error: Environment variables should be UPPERCASE"; exit 1; } || echo "Env naming is correct"
